# Generated by Django 4.2.3 on 2023-07-29 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='own_by',
            field=models.ManyToManyField(related_name='boat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('t_type', models.CharField(choices=[('day', 'day'), ('overnight', 'overnight'), ('nightstay', 'nightstay')], default='overnight', max_length=20)),
                ('ph_no', models.CharField(max_length=12)),
                ('rooms', models.IntegerField(blank=True)),
                ('note', models.CharField(max_length=250)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='booking.boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
